# Generated by Django 3.1.5 on 2021-01-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='机构名称')),
                ('balance', models.FloatField(default=0.0, verbose_name='余额')),
            ],
            options={
                'verbose_name': '组',
            },
        ),
    ]
